--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MulqiGaming64/ServerInfo
build-by-default: true
branches:
- main
projects:
  ServerInfo:
    path: ""
    icon: "icon.png"
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
...
